version: '3.8'

services:
  app-prod:
    container_name: digimon-godesk-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    networks:
      - dgd-prod-network
    environment:
      - APP_ENV=production
      - GO_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dgd-prod-network:
    driver: bridge
