FROM golang:1.23-alpine 

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache git

# Install CompileDaemon for hot reloading
RUN go install github.com/githubnemo/CompileDaemon@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE ${PORT:-8080}

CMD ["CompileDaemon", "-build=go build -o ./tmp/main ./cmd/main.go", "-command=./tmp/main"]
