version: '3'

services:
  digimon-web:
    container_name: digimon-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${EXTERNAL_PORT:-8001}:${PORT:-8080}"
    networks:
      - digimon-network

networks:
  digimon-network:
    driver: bridge