version: '3.8'

# Default docker-compose file (development)
# Use docker-compose.dev.yml for explicit development
# Use docker-compose.prod.yml for production

services:
  app:
    container_name: digimon-godesk
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - dgd-network
    environment:
      - APP_ENV=${APP_ENV:-development}

networks:
  dgd-network:
    driver: bridge