version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    networks:
      - dgd-network

networks:
  dgd-network:
    driver: bridge